version: '3.5'
services:
  kotti:
    build:
      target: development
    container_name: kotti
    depends_on:
      - mono-proxy
    tty: true
    volumes:
      - './kotti/CHANGELOG.md:/app/kotti/CHANGELOG.md:ro'
      - './kotti/nuxt.config.js:/app/kotti/nuxt.config.js:ro'
      - './kotti/packages/:/app/kotti/packages/:ro'
      - './kotti/README.md:/app/kotti/README.md:ro'
      - './kotti/vue.config.js:/app/kotti/vue.config.js:ro'
      - './kotti/docs/:/app/kotti/docs/:ro'
