<template>
	<KtField v-bind="{ field }" :getEmptyValue="() => null" isGroup>
		<div
			:key="forceUpdateKey.value"
			slot="container"
			class="kt-field-radio-group__wrapper"
		>
			<label
				v-for="option in options"
				:key="option.value"
				class="kt-field-radio-group__wrapper__label"
			>
				<input
					v-bind="field.inputProps"
					:checked="field.currentValue === option.value"
					class="kt-field-radio-group__wrapper__input"
					:disabled="field.isDisabled || Boolean(option.disabled)"
					:name="name"
					type="radio"
					:value="option.value"
					@change="onChange(option.value)"
				/>
				<div
					class="kt-field-radio-group__wrapper__radio"
					:class="{
						'kt-field-radio-group__wrapper__radio--checked':
							field.currentValue === option.value,
					}"
				>
					<div class="kt-field-radio-group__wrapper__radio__inside" />
				</div>
				<div v-text="option.label" />
			</label>
		</div>
	</KtField>
</template>

<script lang="ts">
import { defineComponent } from '@vue/composition-api'

import { KtField } from '../kotti-field'
import { ktFieldProps } from '../kotti-field/constants'
import { useField, useForceUpdate } from '../kotti-field/hooks'

import { KtFieldRadioGroup } from './types'

let nameIndex = 0

export default defineComponent({
	name: 'KtFieldRadioGroup',
	components: { KtField },
	props: {
		...ktFieldProps,
		name: {
			default: () => `autoGeneratedRadioName${nameIndex++}`,
			type: String,
		},
		options: {
			required: true,
			type: Array,
			validator: (options: KtFieldRadioGroup.Props['options']) =>
				[...new Set(options.map(({ value }) => value))].length ===
				options.length,
		},
	},
	setup(props: KtFieldRadioGroup.Props, { emit }) {
		const field = useField<KtFieldRadioGroup.Value | null>({
			emit,
			isCorrectDataType: (value): value is KtFieldRadioGroup.Value | null =>
				['number', 'string', 'boolean'].includes(typeof value) ||
				value === null,
			isEmpty: (value) => value === null,
			props,
			supports: {
				clear: false,
				decoration: false,
				placeholder: false,
				tabIndex: true,
			},
		})

		const { forceUpdate, forceUpdateKey } = useForceUpdate()

		return {
			field,
			forceUpdateKey,
			onChange: (value: KtFieldRadioGroup.Entry['value']) => {
				field.setValue(value)
				forceUpdate()
			},
		}
	},
})
</script>

<style lang="scss">
@import '../kotti-field/mixins';

:root {
	--radio-size: 0.8rem;
	--radio-inside-side: 0.2rem;
}

.kt-field-radio-group__wrapper {
	display: flex;
	flex-direction: column;

	&__label {
		display: flex;
		margin-bottom: 0.4rem;
	}

	&__input {
		display: none;
	}

	&__radio {
		display: grid;
		place-items: center;
		width: var(--radio-size);
		height: var(--radio-size);
		margin-right: 0.4rem;
		margin-left: 0.1rem;
		background-color: var(--ui-background);
		border: 1px solid var(--ui-02);
		border-radius: 50%;
		transition: all ease-in-out var(--transition-short);

		&__inside {
			display: block;
			width: var(--radio-inside-side);
			height: var(--radio-inside-side);
			background-color: var(--ui-background);
			border-radius: 50%;
		}

		&--checked {
			background-color: var(--interactive-01);
			border-color: var(--interactive-01);
			box-shadow: var(--shadow-base);
		}
	}
}

.kt-field__wrapper {
	@include validation using ($type) {
		@if $type != no-validation {
			&:not(.kt-field__wrapper--disabled) {
				.kt-field-radio-group__wrapper {
					/* stylelint-disable */
					&__radio {
						border-color: var(--support-#{$type});

						&--checked {
							background-color: var(--support-#{$type});
							box-shadow: var(--shadow-base);
						}
					}
					/* stylelint-enable */
				}
			}
		}
	}

	&--disabled {
		.kt-field-radio-group__wrapper {
			&__label {
				color: var(--text-05);
			}

			&__radio {
				border-color: var(--ui-02);

				&--checked {
					background-color: var(--ui-02);
					box-shadow: var(--shadow-base);
				}
			}
		}
	}
}
</style>
