<template>
	<KtField v-bind="{ field }" :getEmptyValue="() => null" isGroup>
		<div
			:key="forceUpdateKey.value"
			slot="container"
			class="kt-field-radio-group__wrapper"
		>
			<label v-for="option in options" :key="option.value">
				<input
					v-bind="field.inputProps"
					:checked="field.currentValue === option.value"
					:name="name"
					type="radio"
					:value="option.value"
					@change="onChange(option.value)"
				/>
				<div v-text="option.label" />
			</label>
		</div>
	</KtField>
</template>

<script lang="ts">
import { defineComponent } from '@vue/composition-api'

import KtField from '../kotti-field'
import { ktFieldProps } from '../kotti-field/constants'
import { useField, useForceUpdate } from '../kotti-field/hooks'

import { KtFieldRadioGroup } from './types'

let nameIndex = 0

export default defineComponent({
	name: 'KtFieldRadioGroup',
	components: { KtField },
	props: {
		...ktFieldProps,
		name: {
			default: () => `autoGeneratedRadioName${nameIndex++}`,
			type: String,
		},
		options: {
			required: true,
			type: Array,
			validator: (options: KtFieldRadioGroup.Props['options']) =>
				[...new Set(options.map(({ value }) => value))].length ===
				options.length,
		},
	},
	setup(props: KtFieldRadioGroup.Props, { emit }) {
		const field = useField<KtFieldRadioGroup.Value | null>({
			emit,
			isCorrectDataType: (value): value is KtFieldRadioGroup.Value | null =>
				['number', 'string'].includes(typeof value) || value === null,
			props,
		})

		const { forceUpdate, forceUpdateKey } = useForceUpdate()

		return {
			field,
			forceUpdateKey,
			onChange: (value: KtFieldRadioGroup.Entry['value']) => {
				field.setValue(value)
				forceUpdate()
			},
		}
	},
})
</script>

<style lang="scss" scoped>
.kt-field-radio-group__wrapper {
	display: flex;
	flex-direction: column;

	> * {
		display: flex;

		> :not(:first-child) {
			margin-left: 8px;
		}
	}
}
</style>
