<template>
	<KtField v-bind="{ field }" :getEmptyValue="() => null" isGroup>
		<div
			slot="container"
			class="kt-field-radio-group__wrapper"
			:forceUpdateKey="forceUpdateKey"
		>
			<label
				v-for="option in options"
				:key="option.value"
				class="kt-field-radio-group__wrapper__label"
			>
				<input
					v-bind="inputProps"
					:checked="field.currentValue === option.value"
					:disabled="field.isDisabled || Boolean(option.disabled)"
					:value="option.value"
					@change="onChange(option.value)"
				/>
				<div
					class="kt-field-radio-group__wrapper__radio"
					:class="{
						'kt-field-radio-group__wrapper__radio--checked':
							field.currentValue === option.value,
					}"
				>
					<div class="kt-field-radio-group__wrapper__radio__inside" />
				</div>
				<div v-text="option.label" />
			</label>
		</div>
	</KtField>
</template>

<script lang="ts">
import { computed, defineComponent, ref } from '@vue/composition-api'

import { KtField } from '../kotti-field'
import { KOTTI_FIELD_PROPS } from '../kotti-field/constants'
import { useField, useForceUpdate } from '../kotti-field/hooks'

import { KOTTI_FIELD_RADIO_GROUP_SUPPORTS } from './constants'
import { KottiFieldRadioGroup } from './types'

let nameIndex = 0

export default defineComponent({
	name: 'KtFieldRadioGroup',
	components: { KtField },
	props: {
		...KOTTI_FIELD_PROPS,
		options: {
			required: true,
			type: Array,
			validator: (options: KottiFieldRadioGroup.Props['options']) =>
				[...new Set(options.map(({ value }) => value))].length ===
				options.length,
		},
	},
	setup(props: KottiFieldRadioGroup.Props, { emit }) {
		const field = useField<KottiFieldRadioGroup.Value>({
			emit,
			isCorrectDataType: (value): value is KottiFieldRadioGroup.Value =>
				['number', 'string', 'boolean'].includes(typeof value) ||
				value === null,
			isEmpty: (value) => value === null,
			props,
			supports: KOTTI_FIELD_RADIO_GROUP_SUPPORTS,
		})

		const { forceUpdate, forceUpdateKey } = useForceUpdate()
		const name = ref(`autoGeneratedRadioName${nameIndex++}`)

		return {
			inputProps: computed(() => ({
				...field.inputProps,
				class: 'kt-field-radio-group__wrapper__input',
				name,
				type: 'radio',
			})),
			field,
			forceUpdateKey: forceUpdateKey.value,
			onChange: (value: KottiFieldRadioGroup.Entry['value']) => {
				field.setValue(value)

				forceUpdate()
			},
		}
	},
})
</script>

<style lang="scss">
@import '../kotti-field/mixins';

:root {
	--radio-size: 0.8rem;
	--radio-inside-side: 0.2rem;
}

.kt-field-radio-group__wrapper {
	display: flex;
	flex-direction: column;

	&__label {
		display: flex;

		&:not(:last-child) {
			margin-bottom: 0.4rem;
		}
	}

	&__input {
		display: none;
	}

	&__radio {
		display: grid;
		place-items: center;
		width: var(--radio-size);
		height: var(--radio-size);
		margin-right: 0.4rem;
		margin-left: 0.1rem;
		background-color: var(--ui-background);
		border: 1px solid var(--ui-02);
		border-radius: 50%;
		transition: all ease-in-out var(--transition-short);

		&__inside {
			display: block;
			width: var(--radio-inside-side);
			height: var(--radio-inside-side);
			background-color: var(--ui-background);
			border-radius: 50%;
		}

		&--checked {
			background-color: var(--interactive-01);
			border-color: var(--interactive-01);
			box-shadow: var(--shadow-base);
		}
	}
}

.kt-field__wrapper {
	@include validations using ($type) {
		@if $type != no-validation {
			&:not(.kt-field__wrapper--disabled) {
				.kt-field-radio-group__wrapper {
					/* stylelint-disable */
					&__radio {
						border-color: var(--support-#{$type});

						&--checked {
							background-color: var(--support-#{$type});
							box-shadow: var(--shadow-base);
						}
					}
					/* stylelint-enable */
				}
			}
		}
	}

	&--disabled {
		.kt-field-radio-group__wrapper {
			&__label {
				color: var(--text-05);
			}

			&__radio {
				border-color: var(--ui-02);

				&--checked {
					background-color: var(--ui-02);
					box-shadow: var(--shadow-base);
				}
			}
		}
	}
}
</style>
