<template>
	<KtField v-bind="{ field }" :helpTextSlot="$slots.helpText" isGroup>
		<div
			slot="container"
			:class="wrapperClasses"
			:forceUpdateKey="forceUpdateKey"
		>
			<div
				v-for="option in options"
				:key="option.value"
				class="kt-field-radio-group__wrapper__container"
			>
				<div class="kt-field-radio-group__wrapper__header">
					<label
						class="kt-field-radio-group__wrapper__header__label"
						:class="{
							'kt-field-radio-group__wrapper__header__label--disabled':
								field.isDisabled || Boolean(option.isDisabled),
						}"
						:data-test="optionDataTest(option)"
					>
						<div
							class="kt-field-radio-group__wrapper__radio"
							:class="{
								'kt-field-radio-group__wrapper__radio--checked':
									field.currentValue === option.value,
							}"
						>
							<div class="kt-field-radio-group__wrapper__radio__inside" />
						</div>
						<slot name="header" :option="option">
							<div v-text="option.label" />
						</slot>
						<input
							v-bind="inputProps"
							:checked="field.currentValue === option.value"
							:disabled="field.isDisabled || Boolean(option.isDisabled)"
							:value="option.value"
							@change="onChange(option.value)"
						/>
					</label>
					<FieldHelpText
						v-if="option.tooltip"
						class="kt-field-radio-group__wrapper__header__tooltip"
						:helpText="option.tooltip"
					/>
					<slot name="headerSide" :option="option" />
				</div>
				<div class="kt-field-radio-group__wrapper__content">
					<slot name="content" :option="option" />
				</div>
			</div>
		</div>
	</KtField>
</template>

<script lang="ts">
import { omit } from 'lodash'
import { computed, defineComponent, ref } from 'vue'

import { KtField } from '../kotti-field'
import FieldHelpText from '../kotti-field/components/FieldHelpText.vue'
import { useField, useForceUpdate } from '../kotti-field/hooks'
import { makeProps } from '../make-props'

import { KOTTI_FIELD_RADIO_GROUP_SUPPORTS } from './constants'
import { KottiFieldRadioGroup } from './types'

let nameIndex = 0

export default defineComponent<KottiFieldRadioGroup.PropsInternal>({
	name: 'KtFieldRadioGroup',
	components: {
		FieldHelpText,
		KtField,
	},
	props: makeProps(KottiFieldRadioGroup.propsSchema),
	setup(props, { emit }) {
		const field = useField<KottiFieldRadioGroup.Value>({
			emit,
			isEmpty: (value) => value === null,
			props,
			supports: KOTTI_FIELD_RADIO_GROUP_SUPPORTS,
		})

		const { forceUpdate, forceUpdateKey } = useForceUpdate()
		const name = ref(`autoGeneratedRadioName${nameIndex++}`)

		return {
			field,
			forceUpdateKey: forceUpdateKey.value,
			inputProps: computed(
				(): Partial<HTMLInputElement & { class: string }> => ({
					...omit(field.inputProps, ['data-test']),
					class: 'kt-field-radio-group__wrapper__input',
					name: name.value,
					type: 'radio',
				}),
			),
			onChange: (value: KottiFieldRadioGroup.Entry['value']) => {
				field.setValue(value)

				forceUpdate()
			},
			optionDataTest: (option: KottiFieldRadioGroup.Entry) => {
				if (option.dataTest) return option.dataTest

				if (Object.keys(field.inputProps).includes('data-test')) {
					return [field.inputProps['data-test'], option.value].join('.')
				}
			},
			wrapperClasses: computed(() => ({
				'kt-field-radio-group__wrapper': true,
				'kt-field-radio-group__wrapper--inline': props.isInline,
			})),
		}
	},
})
</script>

<style lang="scss">
@import '../kotti-field/mixins';

:root {
	--radio-size: 0.8rem;
	--radio-inside-side: 0.2rem;
}

.kt-field-radio-group__wrapper {
	display: flex;

	&--inline {
		flex-direction: row;

		.kt-field-radio-group__wrapper__container:not(:first-child) {
			margin-left: 1rem;
		}
	}

	&:not(&--inline) {
		flex-direction: column;

		.kt-field-radio-group__wrapper__container:not(:first-child) {
			margin-top: 0.4rem;
		}
	}

	&__header {
		display: flex;
		align-items: flex-start;

		> *:not(:last-child) {
			margin-right: 0.3rem;
		}

		&__label {
			display: flex;
			align-items: flex-start;
			cursor: pointer;

			> *:not(:last-child) {
				margin-right: 0.3rem;
			}

			&--disabled {
				color: var(--text-05);
				cursor: not-allowed;

				.kt-field-radio-group__wrapper__radio {
					border-color: var(--ui-02);

					&--checked {
						background-color: var(--ui-02);
						box-shadow: var(--shadow-base);
					}
				}
			}
		}

		&__tooltip {
			// align tooltip icon with the center of the first line of the label
			// (assumption: font-size comes from common parent element)
			//  > starting point is upper end of the container (flex-start)
			//  > (+0.75em) Put upper edge of element into center (since line-height = 1.5 * font-size)
			//  > (-6px) Put it up half the height of the tooltip height (12px)
			transform: translateY(calc(0.75em - 6px));
		}
	}

	&__input {
		display: none;
	}

	&__radio {
		display: grid;
		flex-shrink: 0;
		place-items: center;
		width: var(--radio-size);
		height: var(--radio-size);
		background-color: var(--ui-background);
		border: 1px solid var(--ui-02);
		border-radius: 50%;
		transition: all ease-in-out var(--transition-short);
		// align radio with the center of the first line of the label
		// (assumption: font-size comes from common parent element)
		//  > starting point is upper end of the container (flex-start)
		//  > (+0.75em) Put upper edge of element into center (since line-height = 1.5 * font-size)
		//  > (-var(--radio-size) * 0.5) Put it up half the height of the radio height
		transform: translateY(calc(0.75em - var(--radio-size) * 0.5));

		&__inside {
			display: block;
			width: var(--radio-inside-side);
			height: var(--radio-inside-side);
			background-color: var(--ui-background);
			border-radius: 50%;
		}

		&--checked {
			background-color: var(--interactive-01);
			border-color: var(--interactive-01);
			box-shadow: var(--shadow-base);
		}
	}

	&__content {
		font-size: var(--font-size-small);
	}
}

.kt-field__wrapper {
	@include validations using ($type) {
		@if $type != empty {
			&:not(.kt-field__wrapper--disabled) {
				.kt-field-radio-group__wrapper {
					/* stylelint-disable */
					&__radio {
						border-color: var(--support-#{$type});

						&--checked {
							background-color: var(--support-#{$type});
							box-shadow: var(--shadow-base);
						}
					}
					/* stylelint-enable */
				}
			}
		}
	}
}
</style>
