name: CI
on:
  push:
    branches-ignore:
      # Ignore branches automatically created by github-rebase
      - rebase-pull-request**
      - cherry-pick-rebase-pull-request**
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install modules
        run: bun install
      - name: Run ESLint
        run: bun run check:eslint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install modules
        run: bun install
      - name: Build packages
        run: bun run turbo run build
      - name: Run tests
        run: bun run test
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install modules
        run: bun install
      - name: Run Prettier
        run: bun run check:prettier
  check-stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install modules
        run: bun install
      - name: Run Stylelint
        run: bun run check:stylelint
  check-knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install modules
        run: bun install
      - name: Run Knip
        run: bun run check:knip
  check-publint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install modules
        run: bun install
      - name: Run Publint
        run: bun run check:publint
  gh-pages-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install modules
        run: bun install
      - name: Build @3yourmind/documentation
        run: bun run turbo run --filter=@3yourmind/documentation build
