name: CI
on:
  push:
    branches-ignore:
      # Ignore branches automatically created by github-rebase
      - rebase-pull-request**
      - cherry-pick-rebase-pull-request**
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run ESLint
        run: yarn run check:eslint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Build @3yourmind/yoco
        run: yarn workspace @3yourmind/yoco run build
      - name: Build @3yourmind/vue-use-tippy
        run: yarn workspace @3yourmind/vue-use-tippy run build
      - name: Run tests
        run: yarn run test
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run Prettier
        run: yarn run check:prettier
  check-stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run Stylelint
        run: yarn run check:stylelint
  check-knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run Knip
        run: yarn run check:knip
  check-publint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run Publint
        run: yarn run check:publint
  gh-pages-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Build @3yourmind/documentation
        run: yarn run turbo run --filter=@3yourmind/documentation build
