name: Jest
on: push
jobs:
  build:
    runs-on: alpine-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install --frozen-lockfile
    - name: Run tests
      run: yarn run test
